# Old world loading

# mvimport old
# mv load old

command /skeg1:
	usage: "Teleport to 2016-2021 Skegcraft 1 world"
	trigger:
		make console execute command "mv tp %player% old"

command /skeg2:
	usage: "Teleport to the Skegcraft 2 world"
	trigger:
		make console execute command "mv tp %player% world"

# Disable portals (end and nether)
#on portal:
#	if player is in "old":
#		cancel event

on command:
	if command sender is not console: 
		if command starts with "mv":
			cancel event
